require:
  - rubocop-rails

Cobra/ViewComponentFilePlacement:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/RedundantConstantBase:
  Exclude:
    - "../**/*component.html.erb"

Style/RedundantPercentQ:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Rails/OutputSafety:
  Enabled: false
