EnableDefaultLinters: true
glob: "*html.erb"

linters:
  RequireInputAutocomplete:
    enabled: false
  NoJavascriptTagHelper:
    enabled: false
  AllowedScriptType:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
        - .erb_rubocop.yml
