# Basic RuboCop configuration for a Ruby project

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - '.git/**/*'
    - 'spec/fixtures/**/*'

# Layout
Layout/LineLength:
  Max: 100

# Style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
  AllowedMethods: ['describe', 'context', 'it', 'before', 'after', 'let', 'let!']

# Linting
Lint/UselessAssignment:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
